name: polaris-react
up:
  - node:
      version: v16.10.0
      yarn: 1.22.15 # to be kept in sync with .nvmrc and ci.yml
  - git_hooks:
      pre-commit: pre-commit

open:
  app: http://localhost:6006/
  shipit: https://shipit.shopify.io/shopify/polaris-react/production

commands:
  # People new to the project might be tempted to run some
  # common commands, so let’s have them in here.
  # For a list of Common Commands in Projects, check out:
  # https://development.shopify.io/tools/dev/getting_started/Common-Commands-in-Projects
  build: yarn run build
  start: yarn run start
  server: yarn run dev
  style: yarn run lint
  test: yarn run test
  type-check: yarn run type-check
